// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzF_XHOzP11cLojGYW2qwkwA_Yh4GYbBg',
    appId: '1:560294573240:android:7f4c648bd25144daf2704d',
    messagingSenderId: '560294573240',
    projectId: 'syteos-labs',
    storageBucket: 'syteos-labs.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsjF_ioqkms7MFRdYYFeKrRlAm_xyoXc',
    appId: '1:560294573240:ios:05cb902d7c1984e1f2704d',
    messagingSenderId: '560294573240',
    projectId: 'syteos-labs',
    storageBucket: 'syteos-labs.firebasestorage.app',
    iosBundleId: 'com.example.syteosBusiness',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx6w8yBzSx3YkngERlbKJePkAp1Vt_cdQ',
    appId: '1:560294573240:web:ed2d36157ed0f2a0f2704d',
    messagingSenderId: '560294573240',
    projectId: 'syteos-labs',
    authDomain: 'syteos-labs.firebaseapp.com',
    storageBucket: 'syteos-labs.firebasestorage.app',
    measurementId: 'G-93N37SDV92',
  );
}
